spring:
  application:
    name: spring-boot-observability

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
   annotations:
    enabled: true

logging:
 level:
  io.micrometer: TRACE
  io.micrometer.dynatrace: TRACE
  org.springframework.boot.actuate.autoconfigure.metrics.export.dynatrace: TRACE
