spring:
  application:
    name: spring-boot-observability

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
   annotations:
    enabled: true
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    enabled: true
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics

  
logging:
 level:
  io.micrometer.registry.otlp: DEBUG
  