spring.application.name=emp-service

spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
management.otlp.metrics.export.enabled=false
management.otlp.metrics.export.url=http://localhost:1234
management.tracing.export.zipkin.enabled=false
management.dynatrace.metrics.export.enabled=false


