server:
  port: 8181
spring:
  profiles:
    active: default
  application:
   name: emp-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:springdb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:P@ssword}
  jpa:
   show-sql: true
   hibernate:
      ddl-auto: update 
  cache:
    type: simple
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    annotations:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
