server:
  port: 8181
spring:
  application:
   name: emp-service
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: P@ssword
  jpa:
   show-sql: true
   hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
  cache:
     type: redis
     redis:
      time-to-live: 20s
