version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  emp-service:
    image: emp-service:1.0
    container_name: emp-service
    restart: unless-stopped
    ports:
      - "8181:8381"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - mynetwork
    depends_on:
      - mysql

networks:
  mynetwork:
    driver: bridge
volumes:
  mysql-data: