
[httpServer]
mgmtMode = auto

[sslConfig]
sslPassword = $7$GQX9myWMlf51b2B3NzVWTrdoz8qArtVqP0ee4X/TvJjcEDnr3a+F1A==

[general]
pass4SymmKey = $7$utXHYk0ANHt3Gv0J+MF8l53axvz6wP3wklzIuRJcoaSpufnvTnrDMQ==

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
