
[httpServer]
mgmtMode = auto

[sslConfig]
sslPassword = $7$ZWJjqY1u4iZXwxxrpJ1afQWYAyv08ie3zbxnD3kj0VX2Sa7Zdk8IzA==

[general]
pass4SymmKey = $7$nvkq588+X8EsncL+2WAff3KLDNASO45iUErnq9m6/j4caRb55m7vFw==

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
