spring:
  application:
    name: spring-boot-observability

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
   annotations:
    enabled: true

  
logging:
 level:
  io.micrometer: DEBUG
 file:
    name: logs/application.log
